# Multi-State FUDS 

- Access <a href="https://drive.google.com/file/d/14K4jDu7Uj07x2kWKAPrGyxLhSK0juQry/view?usp=share_link">homework_fuds.zip</a>.

- Manually unzip this file.

- Write a script that finds only the pdf files and parses all the tables...

- The final product should be a single csv file that contains the FUDS data for all states. (As we noted in class, West Virginian folder includes Wyoming rows).

- You do NOT need to clean the data. Simply get it into a single CSV.

## create more cells as needed

In [56]:
import tabula
import pandas

In [57]:
ph_folder = "all_homework_fuds/{}"
all_files = os.listdir("all_homework_fuds")
all_pdfs = [file for file in all_files if "FUD" in file]
all_paths = [ph_folder.format(pdf) for pdf in all_pdfs]
all_paths

['all_homework_fuds/FUDS_NY.pdf',
 'all_homework_fuds/FUDS_Inventory_WestVirginia.pdf',
 'all_homework_fuds/USACE 2018_FUDS_Inventory_Alaska.pdf']

In [70]:
all_tables = []
for file in all_paths:
    pdf = tabula.read_pdf(file, pages = "all")
    tables = combineTables(pdf,"test.csv")
    df = pd.DataFrame(tables)
    df = df.drop([0])
    all_tables.append(df)

In [71]:
all_data = combineTables(all_tables,"all_fuds.csv")
all_data

,State County,City,Property Name,Property Numbe Site Number Category,Division District,Property Name Property Numbe Site Number,Unnamed: 0,Category,Property Numbe Site Number
0,NY Albany County,ALTAMONT,NORTHEASTERN INDUSTRIAL PARK,C02NY0002 01 HTRW,NAD NAE,NaN,NaN,NaN,NaN
1,NY Albany County,ALTAMONT,NORTHEASTERN INDUSTRIAL PARK,C02NY0002 03 HTRW,NAD NAE,NaN,NaN,NaN,NaN
2,NY Albany County,ALTAMONT,NORTHEASTERN INDUSTRIAL PARK,C02NY0002 04 HTRW,NAD NAE,NaN,NaN,NaN,NaN
3,NY Albany County,ALTAMONT,NORTHEASTERN INDUSTRIAL PARK,C02NY0002 05 HTRW,NAD NAE,NaN,NaN,NaN,NaN
4,NY Clinton County,AU SABLE FORKS,PLATTSBURGH ATLAS S-6,C02NY0211 01 CON/HTRW,NAD NAE,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
757,AK Yakutat Borough,YAKUTAT,YAKUTAT AFB,NaN,POD POA,NaN,NaN,CON/HTRW,F10AK0606 05
758,AK Yakutat Borough,YAKUTAT,YAKUTAT AFB,NaN,POD POA,NaN,NaN,CON/HTRW,F10AK0606 06
759,AK Yakutat Borough,YAKUTAT,YAKUTAT AFB,NaN,POD POA,NaN,NaN,CON/HTRW,F10AK0606 07
760,AK Yakutat Borough,"YAKUTAT, SW. OF",OCEAN CAPE RR SITE,NaN,POD POA,NaN,NaN,CON/HTRW,F10AK0747 01
761,AK Yakutat Borough,"YAKUTAT, SW. OF",OCEAN CAPE RR SITE,NaN,POD POA,NaN,NaN,HTRW,F10AK0747 03

In [27]:
def combineTables(list_name,csv_name):
    '''
    takes multiple dataframes in a list, concats them
    esports to csv
    para1: list name
    para2: csv file name including .csv
    '''
    df = pd.concat(list_name)
    df.reset_index(inplace = True, drop = True)
    df.to_csv(csv_name, encoding = "UTF-8", index = False)
    return df